### ISSUE TITLE
Slider.js:78 / Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by eamaral92** [thebeansgroup/tbg-react-slider#1]
This error keep pop in the console in a loop...

**Comment by eamaral92** [comment]
???

**Comment by eamaral92** [comment]
??????????????????

**Comment by adtaylor** [comment]
Do you have some working code that can be looked at? If I were to guess at the cause of your issue then I'd assume there is no content being passed to the slider.

**Comment by eamaral92** [comment]
<Slider dots='true' arrow={<span></span>} dot={<span></span>} >
			    	<img className="slider-item" src="https://placeholdit.imgix.net/~text?txtsize=86&txt=1026%C3%97480&w=1026&h=480"/>
			    	<img className="slider-item" src="https://placeholdit.imgix.net/~text?txtsize=86&txt=1026%C3%97480&w=1026&h=480"/>
			    	<img className="slider-item" src="https://placeholdit.imgix.net/~text?txtsize=86&txt=1026%C3%97480&w=1026&h=480"/>
				</Slider>

**Comment by eamaral92** [comment]
`<Slider dots='true' arrow={<span></span>} dot={<span></span>} >
                    <img className="slider-item" src="https://placeholdit.imgix.net/~text?txtsize=86&txt=1026%C3%97480&w=1026&h=480"/>
                    <img className="slider-item" src="https://placeholdit.imgix.net/~text?txtsize=86&txt=1026%C3%97480&w=1026&h=480"/>
                    <img className="slider-item" src="https://placeholdit.imgix.net/~text?txtsize=86&txt=1026%C3%97480&w=1026&h=480"/>
                </Slider>`

**Comment by eamaral92** [comment]
Another thing,
I need a thumbnail preview of the imgs, can the slider support that?

**Comment by adtaylor** [comment]
No, the slider does not support thumbnail previews.

Your code appears to work. Working example can be found here: http://www.webpackbin.com/NyfswbaNZ

Closing the issue as there doesn't appear to be an issue. Please reopen if this is not the case.
